version: "3"

services:
  build:
    container_name: openssl_build_android
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /openssl_build
    volumes:
      - ..:/openssl_build
